export const songs = [
  {
    id: "001",
    name: "Guilt",
    author: "Nero",
    album: "Welcome Reality",
    time: "4:44",
  },
  {
    id: "002",
    name: "Elektro",
    author: "Dynoro, Outwork, Mr. Gee",
    album: "Elektro",
    time: "2:22",
  },
  {
    id: "003",
    name: "I’m Fire",
    author: "Ali Bakgor",
    album: "I’m Fire",
    time: "2:22",
  },
  {
    id: "004",
    name: "Non Stop",
    add: "(Remix)",
    author: "Стоункат, Psychopath",
    album: "Non Stop",
    time: "4:12",
  },
  {
    id: "005",
    name: "Run Run",
    add: "(feat. AR/CO)",
    author: "Jaded, Will Clarke, AR/CO",
    album: "Run Run",
    time: "2:54",
  },
  {
    id: "006",
    name: "Eyes on Fire",
    add: "(Zeds Dead Remix)",
    author: "Blue Foundation, Zeds Dead",
    album: "Eyes on Fire",
    time: "5:20",
  },
  {
    id: "007",
    name: "Mucho Bien",
    add: "(Hi Profile Remix)",
    author: "HYBIT, Mr. Black, Offer Nissim, Hi Profile",
    album: "Mucho Bien",
    time: "3:41",
  },
  {
    id: "008",
    name: "Knives n Cherries",
    add: "",
    author: "minthaze",
    album: "Captivating",
    time: "1:48",
  },
  {
    id: "009",
    name: "How Deep Is Your Love",
    add: "",
    author: "Calvin Harris, Disciples",
    album: "How Deep Is Your Love",
    time: "3:32",
  },
  {
    id: "010",
    name: "Morena",
    add: "",
    author: "Tom Boxer",
    album: "Soundz Made in Romania",
    time: "3:36",
  },
];
